export { default as logoImg } from './Logo.png'
export { default as heroBackgroundImg } from './HERO Section.png'
export { default as decorDotImg } from './Ellipse 55.png'
export { default as dashboardMockupImg } from './Rectangle 104.png'
export { default as profileMockupImg } from './Rectangle 103.png'
export { default as findWorkMockupImg } from './Find Work.png'
export { default as maskGroupBgImg } from './Mask Group.png'
export { default as rBadgeImg } from './Group 132.png'
export { default as gruAvatarImg } from './20170315-ShowbizInsider-DespicableMe-696x464-696x430.png'
export { default as paypalImg } from './paypal.png'
